services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5.1
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  
  spark:
    image: bitnami/spark:3.5
    container_name: servo-spark
    environment:
      - SPARK_MODE=client 
    volumes:
      - ../streaming:/app
    command: >
      spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
      /app/stream_job.py
    depends_on:
      - kafka
    ports:
      - "4040:4040"

  servo-simulator:
    build:
      context: ..
      dockerfile: simulator/Dockerfile
    container_name: servo-simulator
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    volumes:
      - ../simulator:/app
      - ../batch/data:/app/data
      - ../serving:/serving:ro
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:latest
    container_name: servo-prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - servo-simulator
